name: Client Tracker Experiment

on:
  workflow_dispatch:

jobs:
  experiment:
    runs-on: windows-latest

    steps:
      - name: Fetch and Extract Dependencies
        run: |
          curl -L -s -o RobloxFileFormat.dll https://github.com/MaximumADHD/Roblox-File-Format/raw/main/RobloxFileFormat.dll
          curl -L -s -o RobloxDeployHistory.dll https://github.com/MaximumADHD/Roblox-Deploy-History/releases/download/v2022.07.20/RobloxDeployHistory.dll 
          curl -L -s -o RobloxAPIDumpTool.exe https://github.com/MaximumADHD/Roblox-API-Dump-Tool/raw/main/RobloxAPIDumpTool.exe 
          curl -L -s -o RobloxStudioModManager.exe https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/raw/main/RobloxStudioModManager.exe
          curl -L -s -o RCT.zip https://github.com/MaximumADHD/RCT-Source/releases/download/v2022.07.20/RCT.zip
          7z x RCT.zip

      - name: List Contents
        run: ls
        
      - name: Run
        run: ./RobloxClientTracker.exe -branch sitetest2.robloxlabs -parent sitetest1.robloxlabs
