name: Client Tracker Experiment

on:
  push:
    branches: [ "main" ]

jobs:
  experiment:
    runs-on: windows-latest
    steps:
      - name:  Fetch RobloxFileFormat.dll
        run:   curl -L -s -o "#1" https://github.com/MaximumADHD/Roblox-File-Format/raw/main/{RobloxFileFormat.dll}
        shell: cmd
        
      - name:  Fetch RobloxDeployHistory.dll
        run:   curl -L -s -o "#1" https://github.com/MaximumADHD/Roblox-Deploy-History/releases/download/v2022.07.20/{RobloxDeployHistory.dll}
        shell: cmd
        
      - name:  Fetch RobloxAPIDumpTool.exe
        run:   curl -L -s -o "#1" https://github.com/MaximumADHD/Roblox-API-Dump-Tool/raw/main/{RobloxAPIDumpTool.exe}
        shell: cmd
        
      - name:  Fetch RobloxStudioModManager.exe
        run:   curl -L -s -o "#1" https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/raw/main/{RobloxStudioModManager.exe}
        shell: cmd
        
      - name:  Fetch RCT.zip
        run:   curl -L -s -o "#1" https://github.com/MaximumADHD/RCT-Source/releases/download/v2022.07.20/{RCT.zip}
        shell: cmd
        
      - name:  Extract RCT.zip
        run:   7z x RCT.zip
        shell: cmd
      
      - name:  Checkout Roblox-Client-Tracker
        uses:  actions/checkout@v3
        with:
          repository: 'MaximumADHD/Roblox-Client-Tracker'
          ssh-key: ${{ secrets.CLIENT_TRACKER_SSH }}
          ref: 'sitetest2.robloxlabs'
        
      - name:  Run Client Tracker
        run:   RobloxClientTracker.exe -branch sitetest2.robloxlabs -parent sitetest1.robloxlabs
        shell: cmd
