name: Client Tracker Experiment

on:
  workflow_dispatch:

jobs:
  experiment:
    runs-on: windows-latest
    env:
      CLIENT_TRACKER_SSH:  ${{ secrets.CLIENT_TRACKER_SSH }}
    steps:
      - name: Fetch RobloxFileFormat.dll
        run:  curl -L -s -o "#1" https://github.com/MaximumADHD/Roblox-File-Format/raw/main/{RobloxFileFormat.dll}

      - name: Fetch RobloxDeployHistory.dll
        run:  curl -L -s -o "#1" https://github.com/MaximumADHD/Roblox-Deploy-History/releases/download/v2022.07.20/{RobloxDeployHistory.dll}

      - name: Fetch RobloxAPIDumpTool.exe
        run:  curl -L -s -o "#1" https://github.com/MaximumADHD/Roblox-API-Dump-Tool/raw/main/{RobloxAPIDumpTool.exe}
      
      - name: Fetch RobloxStudioModManager.exe
        run:  curl -L -s -o "#1" https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/raw/main/{RobloxStudioModManager.exe}
        
      - name: Fetch RCT.zip
        run:  curl -L -s -o "#1" https://github.com/MaximumADHD/RCT-Source/releases/download/v2022.07.20/{RCT.zip}
        
      - name: Extract RCT.zip
        run:  7z x RCT.zip
        
      - name: Create ~/.ssh
        run:  New-Item -ItemType Directory -Force -Path $env:UserProfile/.ssh
        
      - name: Write ~/.ssh/RobloxClientTracker
        run:  echo $CLIENT_TRACKER_SSH | base64 --decode > $env:UserProfile/.ssh/RobloxClientTracker"
        
      - name: Run
        run: ./RobloxClientTracker.exe -branch sitetest2.robloxlabs -parent sitetest1.robloxlabs
