name: Client Tracker Experiment

on:
  workflow_dispatch:

jobs:
  experiment:
    runs-on: windows-latest

    steps:
      - name: Fetch RobloxFileFormat.dll
        run: curl https://github.com/MaximumADHD/Roblox-File-Format/raw/main/RobloxFileFormat.dll -o RobloxFileFormat.dll
        
      - name: Fetch RobloxDeployHistory.dll
        run: curl https://github.com/MaximumADHD/Roblox-Deploy-History/releases/download/v2022.07.20/RobloxDeployHistory.dll -o RobloxDeployHistory.dll
        
      - name: Fetch RobloxApiDumpTool.exe
        run: curl https://github.com/MaximumADHD/Roblox-API-Dump-Tool/raw/main/RobloxAPIDumpTool.exe -o RobloxAPIDumpTool.exe
        
      - name: Fetch RobloxStudioModManager.exe
        run: curl https://github.com/MaximumADHD/Roblox-Studio-Mod-Manager/raw/main/RobloxStudioModManager.exe

      - name: Fetch RCT.zip
        run: curl https://github.com/MaximumADHD/RCT-Source/releases/download/v2022.07.20/RCT.zip -o RCT.zip
                        
      - name: Extract RCT.zip
        run: tar -xf RCT.zip
        
      - name: Run Client Tracker
        run: ./RobloxClientTracker.exe -branch sitetest2.robloxlabs -parent sitetest1.robloxlabs
